# Generated by Django 4.0.6 on 2022-07-11 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='coutry_code',
            new_name='country_code',
        ),
    ]
